name: "Publish the cassini crate to crates.io"
on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1.4.0
        with:
          rust-version: stable

      - name: Publish to crates.io
        shell: bash
        run: |
          cargo clean
          RUSTFLAGS='-C target-feature=+crt-static' cargo publish --token ${CRATES_TOKEN}
